import "./globals.css";
import LenisSmoothScroll from "../components/LenisSmoothScroll";
import LayoutTransition from "@/components/LayoutTransition";

export const metadata = {
  title: "MONIELINK",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <LenisSmoothScroll />
      <html lang="en">
        <body>
          <LayoutTransition>
          {children}
          </LayoutTransition>
        </body>
      </html>
    </>
  );
}
