import "./globals.css";
import LenisSmoothScroll from "./components/LenisSmoothScroll";
import localFont from "next/font/local";

const Roobert = localFont({
  src: [
    { path: "./fonts/RoobertTRIAL-Light.woff2", weight: "300", style: "normal" },
    { path: "./fonts/RoobertTRIAL-Regular.woff2", weight: "400", style: "normal" },
    { path: "./fonts/RoobertTRIAL-Medium.woff2", weight: "500", style: "normal" },
    { path: "./fonts/RoobertTRIAL-SemiBold.woff2", weight: "600", style: "normal" },
    { path: "./fonts/RoobertTRIAL-Bold.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-body",
  display: "swap",
  fallback: ["system-ui, sans-serif"],
})
const TWK = localFont({
  src: [
    { path: "./fonts/TWKLausanne.woff2", weight: "400", style: "normal" },
  ],
  variable: "--font-display",
  display: "swap",
  fallback: ["system-ui, sans-serif"],
})
export const metadata = {
  title: "MONIELINK",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
    <LenisSmoothScroll/>
    <html lang="en">
      <body
        className={`${Roobert.variable} ${TWK.variable} antialiased`}
      >
        {children}
      </body>
    </html>
    </>
  );
}
